### ISSUE TITLE
Cromwell possibly adding extra "resources" stanza with JES Backend

### ISSUE THREAD

**Issue by jsotobroad** [broadinstitute/cromwell#1501]
It looks like with .21 there is a an extra `resources` key with default values in the pipeline args section when you describe a jes job.  When I ran the 50 workflow test with .21 none of my jobs seemed to get preempted which seems unusual and I want to make sure this extra `resources` stanza with default values isn't causing issues.

from .19:
```
resources:
        bootDiskSizeGb: 10
        disks:
        - autoDelete: true
          mountPoint: /cromwell_root
          name: local-disk
          sizeGb: 208
          type: PERSISTENT_HDD
        minimumCpuCores: 1
        minimumRamGb: 10
        preemptible: true
        zones:
        - us-central1-b
        - us-central1-c
    pipelineArgs:
      clientId: ''
      inputs:
        exec: gs://broad-gotc-prod-cromwell-execution/PairedEndSingleSampleWorkflow/0e160d60-4f48-4058-84c3-36351a7b2cbd/call-HaplotypeCaller/shard-17/exec.sh
        input_bam-0: gs://broad-gotc-prod-cromwell-execution/PairedEndSingleSampleWorkflow/0e160d60-4f48-4058-84c3-36351a7b2cbd/call-GatherBamFiles/NWD989972.bam
        input_bam_index-0: gs://broad-gotc-prod-cromwell-execution/PairedEndSingleSampleWorkflow/0e160d60-4f48-4058-84c3-36351a7b2cbd/call-GatherBamFiles/NWD989972.bai
        interval_list-0: gs://broad-references/hg38/v0/scattered_calling_intervals/temp_0018_of_50/scattered.interval_list
        ref_dict-0: gs://broad-references/hg38/v0/Homo_sapiens_assembly38.dict
        ref_fasta-0: gs://broad-references/hg38/v0/Homo_sapiens_assembly38.fasta
        ref_fasta_index-0: gs://broad-references/hg38/v0/Homo_sapiens_assembly38.fasta.fai
      logging:
        gcsPath: gs://broad-gotc-prod-cromwell-execution/PairedEndSingleSampleWorkflow/0e160d60-4f48-4058-84c3-36351a7b2cbd/call-HaplotypeCaller/shard-17/HaplotypeCaller-17.log
      outputs:
        HaplotypeCaller-17-rc.txt: gs://broad-gotc-prod-cromwell-execution/PairedEndSingleSampleWorkflow/0e160d60-4f48-4058-84c3-36351a7b2cbd/call-HaplotypeCaller/shard-17/HaplotypeCaller-17-rc.txt
        NWD989972.vcf.gz: gs://broad-gotc-prod-cromwell-execution/PairedEndSingleSampleWorkflow/0e160d60-4f48-4058-84c3-36351a7b2cbd/call-HaplotypeCaller/shard-17/NWD989972.vcf.gz
        NWD989972.vcf.gz.tbi: gs://broad-gotc-prod-cromwell-execution/PairedEndSingleSampleWorkflow/0e160d60-4f48-4058-84c3-36351a7b2cbd/call-HaplotypeCaller/shard-17/NWD989972.vcf.gz.tbi
      projectId: broad-gotc-prod
      serviceAccount:
        email: default
        scopes:
        - https://www.googleapis.com/auth/compute
        - https://www.googleapis.com/auth/devstorage.full_control
        - https://www.googleapis.com/auth/genomics
        - https://www.googleapis.com/auth/devstorage.full_control
        - https://www.googleapis.com/auth/devstorage.read_write
        - https://www.googleapis.com/auth/genomics
        - https://www.googleapis.com/auth/compute
  runtimeMetadata:
    '@type': type.googleapis.com/google.genomics.v1alpha2.RuntimeMetadata
    computeEngine:
      diskNames:
      - local-disk-15719508696139283496
      instanceName: ggp-15719508696139283496
      machineType: us-central1-c/n1-highmem-2
      zone: us-central1-c
  startTime: '2016-09-28T07:20:39Z'
name: operations/EIf5mP32Khio-K6o-ru6k9oBIJ-ikOmeDSoPcHJvZHVjdGlvblF1ZXVl
```

from .21:

```
resources:
        bootDiskSizeGb: 10
        disks:
        - autoDelete: true
          mountPoint: /cromwell_root
          name: local-disk
          sizeGb: 200
          type: PERSISTENT_HDD
        minimumCpuCores: 1
        minimumRamGb: 7
        preemptible: true
        zones:
        - us-central1-b
        - us-central1-c
    pipelineArgs:
      clientId: ''
      inputs:
        exec: gs://broad-gotc-int-cromwell-execution/PairedEndSingleSampleWorkflow/4d02d218-b473-4a88-8820-964da7e508c4/call-ValidateReadGroupSamFile/shard-22/exec.sh
        input_bam-0: gs://broad-gotc-int-cromwell-execution/PairedEndSingleSampleWorkflow/4d02d218-b473-4a88-8820-964da7e508c4/call-SortAndFixReadGroupBam/shard-22/HTC3GCCXX.8.Pond-536132.sorted.bam
        ref_dict-0: gs://broad-references/hg38/v0/Homo_sapiens_assembly38.dict
        ref_fasta-0: gs://broad-references/hg38/v0/Homo_sapiens_assembly38.fasta
        ref_fasta_index-0: gs://broad-references/hg38/v0/Homo_sapiens_assembly38.fasta.fai
      logging:
        gcsPath: gs://broad-gotc-int-cromwell-execution/PairedEndSingleSampleWorkflow/4d02d218-b473-4a88-8820-964da7e508c4/call-ValidateReadGroupSamFile/shard-22/ValidateReadGroupSamFile-22.log
      outputs:
        HTC3GCCXX.8.Pond-536132.validation_report: gs://broad-gotc-int-cromwell-execution/PairedEndSingleSampleWorkflow/4d02d218-b473-4a88-8820-964da7e508c4/call-ValidateReadGroupSamFile/shard-22/HTC3GCCXX.8.Pond-536132.validation_report
        ValidateReadGroupSamFile-22-rc.txt: gs://broad-gotc-int-cromwell-execution/PairedEndSingleSampleWorkflow/4d02d218-b473-4a88-8820-964da7e508c4/call-ValidateReadGroupSamFile/shard-22/ValidateReadGroupSamFile-22-rc.txt
      projectId: broad-gotc-int
      resources:
        bootDiskSizeGb: 0
        disks: []
        minimumCpuCores: 0
        minimumRamGb: 0
        noAddress: false
        preemptible: false
        zones: []
      serviceAccount:
        email: default
        scopes:
        - https://www.googleapis.com/auth/compute
        - https://www.googleapis.com/auth/devstorage.full_control
        - https://www.googleapis.com/auth/genomics
        - https://www.googleapis.com/auth/genomics
        - https://www.googleapis.com/auth/compute
  runtimeMetadata:
    '@type': type.googleapis.com/google.genomics.v1alpha2.RuntimeMetadata
    computeEngine:
      diskNames:
      - local-disk-12146155240789544851
      instanceName: ggp-12146155240789544851
      machineType: us-central1-b/n1-standard-2
      zone: us-central1-b
  startTime: '2016-09-28T04:07:00Z'
name: operations/EPuKyPf2KhiTn4qQ6vrzx6gBINj5z_mlEioPcHJvZHVjdGlvblF1ZXVl
```
