### ISSUE TITLE
Honour custom stdout locations

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#2764]
Eg in the step:

```yaml
steps:
- id: ps
  in: []
  out:
  - id: ps-stdOut
  run:
    inputs: []
    outputs:
    - id: ps-stdOut
      outputBinding:
        glob: ps-stdOut.txt
      type: File
    class: CommandLineTool
    baseCommand: ps
    stdout: ps-stdOut.txt
```
