### ISSUE TITLE
Array Input syntax bug

### ISSUE THREAD

**Issue by ruchim** [broadinstitute/cromwell#3588]
When using the type `string[]` along with the key `prefix`, instead of the prefix being added at the head of string array, the prefix is being applied to each element, along with the head of the list of elements.

Example CWL:
```
#!/usr/bin/env cwl-runner
cwlVersion: v1.0
class: CommandLineTool
baseCommand: ['/bin/echo']
stdout: "hello.txt"
inputs:
    bonus:
        type: string[]
        inputBinding:
            prefix: "--bonus"
outputs:
    hello:
        type: stdout
```

Example  Inputs:
```
bonus: ["first", "second"]
```

Actual Response:
```
[2018-05-02 15:19:13,62] [info] BackgroundConfigAsyncJobExecutionActor [93064d21test.cwl:NA:1]: '/bin/echo' '--bonus' '--bonus' 'first' '--bonus' 'second'
```

Expected Response: http://www.commonwl.org/user_guide/09-array-inputs/
```
'/bin/echo' '--bonus' 'first' 'second'
```
