### ISSUE TITLE
issues when running cromwell as part of the docker swarm

### ISSUE THREAD

**Issue by antonkulaga** [broadinstitute/cromwell#3910]
Hello, I am trying to deploy and use cromwell as a docker swarm stack and I have some serios problems with it. 
My configuration that I have in production is https://github.com/antonkulaga/cromwell-client/tree/master/services/pipelines.yml
As current broad container does not have docker inside (and thus cannot spawn tasks with docker runtimes) I had to:
* make a custom cromwell container that inherits from the official one and contains docker ( https://github.com/antonkulaga/cromwell-client/tree/master/services/cromwell )
* use 
```yml
 volumes:
  - /var/run/docker.sock:/var/run/docker.sock
```
trick, to spawn docker containers as sibling to cromwell container.
Unfortunately when running this setup I discovered that when I configure cromwell execution directory to an absolute path, like "/pipelines/cromwell-executions" the the script file that was generated by cromwell for each task still used /cromwell-executions I had to mount an extra volume to trick it.
The other problem is that it constantly having errors like this:
```
Workflow failed

WorkflowFailure(Unable to determine that 190 is alive, and /pipelines/cromwell-executions/vsearch/1ab35317-b0ae-4e7b-8b09-3403cdaff125/call-global_search/execution/rc does not exist.,List())
```
while rc file does exist (checked it both on host system and volume). My bet is that it is somehow related with having cromwell inside docker.

**Comment by suecharo** [comment]
I write this as a note.
I also tried to run cromwell with docker sibling (using `docker.sock` on the host machine).
It worked with the code below.

`docker-compose.yml`

```
version: "3"
services:
  app:
    image: broadinstitute/cromwell:55
    entrypoint: [""]
    command: ["sleep", "infinity"]
    volumes:
      - ${PWD}:${PWD}
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
      - /usr/bin/docker:/usr/bin/docker
    working_dir: ${PWD}
```

```
$ docker-compose up -d
$ docker-compose exec app java -jar /app/cromwell.jar run ${PWD}/path/to/workflow -i ${PWD}/path/to/workflow_param
```
