### ISSUE TITLE
Use varnish web cache to mitigate "thundering herd" request problem

### ISSUE THREAD

**Issue by danbills** [broadinstitute/cromwell#4253]
I found a formal name for the approach of pooling identical requests and sending one to the server, it is "[request coalescing](https://varnish-cache.org/docs/6.1/users-guide/vcl-grace.html#grace-mode)".  

There is an off-the-shelf "caching HTTP reverse proxy" known as [varnish](https://varnish-cache.org/docs/6.1/index.html) which can do this for us.

This is probably best implemented as a caching/ request coalescing layer above cromwell.  

This came a result of discussion around #4226.

**Comment by danbills** [comment]
The following gives a 2 GB cache on top of Cromwell, and forwards aborts to a different host.  I've manually tested with the following configuration as an excuse to play w/ Kubernetes:

## Varnish config

points all queries to reader service except aborts:
```
vcl 4.0;

backend worker {
  .host = "cromwell-worker-service.default";
  .port = "8000";
}

backend reader {
  .host = "cromwell-reader-service.default";
  .port = "8000";
}

sub vcl_recv {
    if (req.url ~ "abort/$") {
        set req.backend_hint = worker;
    } else {
        set req.backend_hint = reader;
    }
}
```
Source: https://raw.githubusercontent.com/danbills/ammoniteExample/master/kubernetes/varnish-rw-cromwell-config.vcl

## Varnish docker 

w/ latest 6.1 version:
https://hub.docker.com/r/danbills/varnish/
Source: https://github.com/danbills/ammoniteExample/tree/master/kubernetes/varnish

## Kubernetes Config(map)
Kubernetes [Pod](https://kubernetes.io/docs/concepts/workloads/pods/pod-overview/) to run varnish w/ the config file loaded into a [ConfigMap](https://cloud.google.com/kubernetes-engine/docs/concepts/configmap) named `rw`:
```
apiVersion: v1
kind: Pod
metadata:
  name: varnish-cache
  labels:
      app: varnish-cache
spec:
  containers:
  - name: cache
    resources:
      requests:
        # We'll use two gigabytes for each varnish cache
        memory: 2Gi
    image: danbills/varnish:6_1
    imagePullPolicy: Always
    args: ["-F", "-f", "/conf/varnish-rw-cromwell-config.vcl", "-a" , "0.0.0.0:8080" , "-s" , "malloc,2G"]
    ports:
    - containerPort: 8080
    volumeMounts:
    - name: config-volume
      mountPath: /conf
  volumes:
    - name: config-volume
      configMap:
        # Provide the name of the ConfigMap containing the files you want
        # to add to the container
        name: rw
```
