### ISSUE TITLE
CWL: DockerRequirement + InitialWorkDirRequirement returns host path, but not mapped path 

### ISSUE THREAD

**Issue by Shenglai** [broadinstitute/cromwell#4533]
I want reduce the length of bash command line when perform the joint-genotyping on thousands samples, so that I'm using InitialWorkDirRequirement to create a file path list.

Here's the example CWL:
```
#!/usr/bin/env cwl-runner

cwlVersion: v1.0

class: CommandLineTool

requirements:
  - class: InlineJavascriptRequirement
  - class: DockerRequirement
    dockerPull: quay.io/shenglai/alpine_with_bash:1.0
  - class: InitialWorkDirRequirement
    listing:
      - entryname: "files.json"
        entry: $(inputs.files.basename)
inputs:
  files: File

outputs:
  output:
    type: File
    outputBinding:
      glob: "files.json"

baseCommand: []
```
the input is
```
{
  "files": {"class": "File", "path": "/mnt/glusterfs/a.file"}
}
```
the cwltool output `files.json` is

```
{"basename":"a.file","nameroot":"a","nameext":".file","location":"file:///mnt/glusterfs/a.file","path":"/var/lib/cwl/stg1a204114-8318-47ee-b5d0-7454ab87f7df/a.file","dirname":"/var/lib/cwl/stg1a204114-8318-47ee-b5d0-7454ab87f7df","class":"File","size":0}
```

the cromwell one is
```
{"nameext":".file","location":"/mnt/glusterfs/a.file","path":"/mnt/glusterfs/a.file","size":0,"dirname":"/mnt/glusterfs","secondaryFiles":[],"basename":"a.file","class":"File","nameroot":"a"}
```

As you can see, from cwltool, it actually returns a mapped path under `path`, so the later docker command can pick that up.
On the other hand, cromwell only returns the host path, which can not be found in docker.

I only tested the piece with SLURM. I would assume it also fails on local run.

**Comment by illusional** [comment]
+1 to this issue as well, Cromwell is correctly placing the file into the execution directory, but it's not correctly mapping the path in the command. My issue specifically:

Issue: I need `file.txt` to be in the execution directory, however when constructing the command it uses the original path to the file in the `inputs/` directory:
```
'cat' '/path/to/cromwell-executions/.../inputs/1450116529/file.txt'
```

when it should be:
```
'cat' '/path/to/cromwell-executions/.../execution/file.txt'
```

For me, this is important for tools (like `tabix`) that only produce their files at the source of the original file, and it's hard to glob outside the execution directory.

----
CommandLineTool:
```cwl
baseCommand: cat
class: CommandLineTool
cwlVersion: v1.0
id: ListDirectory
inputs:
  file:
    inputBinding:
      position: 5
    label: file_to_localise
    type: File
outputs:
  out: 
    type: File
    outputBinding:
      glob: $(inputs.file.basename) # breaks without .basename
requirements:
  InitialWorkDirRequirement:
    listing:
    - $(inputs.file)
  InlineJavascriptRequirement: {}
```
Inputs:
```yaml
file:
  class: File
  path: /path/to/file.txt
```
