### ISSUE TITLE
CWL: Workflow requirements not inheriting to as required by specification

### ISSUE THREAD

**Issue by whlavina** [broadinstitute/cromwell#4544]
Per the CWL Specifications, section 3.3:

> Requirements are inherited. A requirement specified in a Workflow applies to all workflow steps; a requirement specified on a workflow step will apply to the process implementation of that step and any of its substeps.

It appears that Cromwell does not correctly implement the above. For example, a `dockerPull` requirement specified in a workflow, does not get applied to a command in a subworkflow.

Cromwell version: `cromwell-36`

`test.cwl`
```
#!/usr/bin/env cwl-runner

cwlVersion: v1.0
class: Workflow

requirements:
  - class: SubworkflowFeatureRequirement
  - class: DockerRequirement
    dockerPull: ubuntu

inputs: []

steps:
  substep:
    run: subworkflow.cwl
    in: []
    out: [container]
 
outputs:
  container:
    type: File
    outputSource: substep/container
```

`subworkflow.cwl`
```
#!/usr/bin/env cwl-runner

cwlVersion: v1.0
class: Workflow

requirements:
  - class: SubworkflowFeatureRequirement

inputs: []

steps:
  substep:
    run: command.cwl
    in: []
    out: [container]
 
outputs:
  container:
    type: File
    outputSource: substep/container
```

`command.cwl`
``` 
cwlVersion: v1.0 
class: CommandLineTool

baseCommand: ['grep', 'docker', '/proc/1/cgroup']

inputs: []
outputs:
  container:
    type: stdout
```

`test.yaml`
```
{}
```
