### ISSUE TITLE
imports zip file with a subdir causes errors

### ISSUE THREAD

**Issue by notestaff** [broadinstitute/cromwell#4969]
With Cromwell 41, when submitting an imports.zip containing workflow imports, if the zipfile has a subdirectory, I get these errors:

2019-05-14 11:05:38,560 cromwell-system-akka.dispatchers.engine-dispatcher-101 ERROR - WorkflowManagerActor Workflow a3fb73f1-2976-456\
3-a691-a356e2744dda failed (during MaterializingWorkflowDescriptorState): cromwell.engine.workflow.lifecycle.materialization.Materiali\
zeWorkflowDescriptorActor$$anon$1: Workflow input processing failed:
/tmp/imports_workflow_a3fb73f1-2976-4563-a691-a356e2744dda_9012613107684347004.zip7783627211874195701/tasks/tasks_assembly.wdl
        at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.cromwell$engine$workflow$lifecycle$ma\
terialization$MaterializeWorkflowDescriptorActor$$workflowInitializationFailed(MaterializeWorkflowDescriptorActor.scala:215)
        at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anonfun$2.applyOrElse(MaterializeWor\
kflowDescriptorActor.scala:185)
        at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anonfun$2.applyOrElse(MaterializeWor\
kflowDescriptorActor.scala:180)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:34)
        at akka.actor.FSM.processEvent(FSM.scala:684)
        at akka.actor.FSM.processEvent$(FSM.scala:681)
        at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.akka$actor$LoggingFSM$$super$processE\
vent(MaterializeWorkflowDescriptorActor.scala:136)
        at akka.actor.LoggingFSM.processEvent(FSM.scala:820)
        at akka.actor.LoggingFSM.processEvent$(FSM.scala:802)
        at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.processEvent(MaterializeWorkflowDescr\
iptorActor.scala:136)
        at akka.actor.FSM.akka$actor$FSM$$processMsg(FSM.scala:678)
        at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:672)
        at akka.actor.Actor.aroundReceive(Actor.scala:517)
        at akka.actor.Actor.aroundReceive$(Actor.scala:515)
        at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.aroundReceive(MaterializeWorkflowDesc\
riptorActor.scala:136)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
        at akka.actor.ActorCell.invoke(ActorCell.scala:557)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
        at akka.dispatch.Mailbox.run(Mailbox.scala:225)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

2019-05-14 11:05:38,561 cromwell-system-akka.dispatchers.engine-dispatcher-101 INFO  - WorkflowManagerActor WorkflowActor-a3fb73f1-297\
6-4563-a691-a356e2744dda is in a terminal state: WorkflowFailedState

**Comment by jeremiahsavage** [comment]
I just encountered this error, as well. I narrowed it down to this commit.

**Comment by geoffjentry** [comment]
Thanks @jeremiahsavage 

@notestaff Were you using WDL or CWL?

**Comment by jeremiahsavage** [comment]
Example test case:

`wf.cwl`:
```
#!/usr/bin/env cwl-runner

cwlVersion: v1.0

class: Workflow

inputs:
  - id: astring
    type: string

outputs:
  - id: afile
    type: File
    outputSource: touch/output

steps:
  - id: touch
    run: cwl/touch.cwl
    in:
      - id: input
        source: astring
    out:
      - id: output
```

in `cwl/touch.cwl`:
```
#!/usr/bin/env cwl-runner

cwlVersion: v1.0

requirements:
  - class: DockerRequirement
    dockerPull: ubuntu:bionic-20180426

class: CommandLineTool

inputs:
  - id: input
    type: string
    inputBinding:
      position: 0

outputs:
  - id: output
    type: File
    outputBinding:
      glob: $(inputs.input)
      
baseCommand: [touch]
```
then zip the dir:
```
zip -r cwl.zip cwl
```
test input `wf.json`:
```
{
    "astring": "hello"
}
```
